version: "3.8"

volumes:
    re-store-mysql-data:
    re-store-minio-data:
    re-store-rabbitmq-data:

services:
    mysqldb:
        restart: always
        image: mysql
        container_name: re-store-mysqldb
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
        environment:
            - MYSQL_DATABASE=re_store
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - re-store-mysql-data:/var/lib/mysql
            - ./mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql
        ports:
            - "3306:3306"
    
    minio:
        restart: always
        image: minio/minio:RELEASE.2021-04-06T23-11-00Z
        container_name: re-store-minio
        command: server /data/minio
        environment:
            MINIO_ROOT_USER: re_store
            MINIO_ROOT_PASSWORD: restore123
        volumes: 
            - re-store-minio-data:/data
        ports:
            - "9000:9000"
    
    rabbitmq:
        image: rabbitmq:3-management
        container_name: re-store-rabbitmq
        environment:
            - RABBITMQ_ERLANG_COOKIE=123123
            - RABBITMQ_DEFAULT_USER=re_store
            - RABBITMQ_DEFAULT_PASS=restore123
        volumes:
            - re-store-rabbitmq-data:/var/lib/rabbitmq
        ports:
            - 5672:5672     # Do Not Uncomment in Production
            - 15672:15672
    