version: "3.8"

volumes:
    re-store-mysqldata:

services:
    mysqldb:
        restart: always
        image: mysql
        container_name: mysqldb
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4
        environment:
            - MYSQL_DATABASE=forum_learning
            - MYSQL_ROOT_PASSWORD=root
        volumes:
            - re-store-mysqldata:/var/lib/mysql
            - ./mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql
    